[[data]]
predictor = "Narasimha Rao"
time = "2016"
outcome_time = "2017"
prediction = "Trump will loose to Hilary clinton."
prediction_text = '''
Facebook post deleted as soon as it was pointed out that he was wrong.
'''
success = false

[[data]]
predictor = "Narasimha Rao"
time = "2020-05-23"
prediction = "Tibetan independence by 2030"
outcome_time = "2030"
prediction_text = '''
'''
urls = ["https://www.youtube.com/watch?v=lKpPaKIvN5c"]

[[data]]
predictor = "Narasimha Rao"
time = "2020-08-12"
outcome_time = "2021"
prediction = "Trump will loose to Kamala harris."
prediction_text = '''
I have waited till now to predict the outcome of 2020 election, though I have been very vocal that Trump transitioned in June 2020 from an awesome long-term dasa (life phase) to an awful one. It is because I was not too confident of the accuracy of Joe Biden's birth time (the unreliable time we have suggested that he will win, but after some delay till at least late November). But now I am ready to make a prediction, as I am confident of the birth data of senator Kamala Devi Harris, whom Joe Biden picked as his running mate. I will later post a video with my astrological analysis based on rasi, navamsa, dasamsa and shashtyamsa of natal, annual solar and annual lunar charts, but here is my bottom line prediction.
Senator Harris is running a period of great fortune in several ways and her annual charts of 2020-21 also look fantastic, from the perspective of political power. She will enjoy victory in the 2020 election. She is the next Vice President, or even President, of US.
She is intelligent, clever, calculative, sharp, articulate, worldly wise, highly pragmatic and, above all, very fortunate. She is not overly idealistic, but can project idealism when that is the best strategy per her calculation.
I expect her to be reasonably friendly towards India, but not really a great friend of Hinduism.
'''
urls = ["https://i.imgur.com/4bTEtHK.png", "https://archive.vn/yYeU3"]